// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_key_from_password`, `generate_nonce`

(Uint8List, Uint8List) encryptNote({
  required String note,
  required String password,
}) => RustLib.instance.api.crateApiEncryptionEncryptNote(
  note: note,
  password: password,
);

String decryptNote({
  required List<int> nonce,
  required List<int> encryptedNote,
  required String password,
}) => RustLib.instance.api.crateApiEncryptionDecryptNote(
  nonce: nonce,
  encryptedNote: encryptedNote,
  password: password,
);
